name: Build, Push, and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push Docker image with commit SHA as tag
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            juanitoramos456/todo-app:latest
            juanitoramos456/todo-app:${{ github.sha }}

      # Deploy to VM via SSH
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull juanitoramos456/todo-app:latest
            # Stop existing container if exists
            docker stop todo-app || true
            docker rm todo-app || true
            # Run new container
            docker run -d --name todo-app -p 80:80 juanitoramos456/todo-app:latest
