name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: juanitoramos456/todo-app:latest

  deploy-to-vm:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Copy and Run on VM
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull juanitoramos456/todo-app:latest
            docker stop todo-app || true
            docker rm todo-app || true
            docker run -d --name todo-app -p 8080:80 juanitoramos456/todo-app:latest
